# this is adapted from Atari configuration (with a slightly higher exploration eps), may get better results with some tuning
ALG_NAME: "pqn-resid"
TOTAL_TIMESTEPS: 30000000
TOTAL_TIMESTEPS_DECAY: 30000000 # will be used for decay functions, in case you want to test for less timesteps and keep decays same
NUM_ENVS: 128 # parallel environments
NUM_STEPS: 32 # steps per environment in each update
EPS_START: 1.
EPS_FINISH: 0.05
EPS_DECAY: 0.1 # ratio of total updates
NUM_MINIBATCHES: 32 # minibatches per epoch
NUM_EPOCHS: 2 # minibatches per epoch
NORM_TYPE: "justnorm" # layer_norm, batch_norm, or justnorm
MLP_NUM_LAYERS: 1
MLP_HIDDEN_DIM: 128
USE_ROPE: False
ROPE_THETA: 10000.0
LR: 0.0005
MAX_GRAD_NORM: 10
PER_LAYER_GRADIENT_CLIPPING: False
K: 0 # singularclip interval in gradient steps; 0 disables singularclip
c: 1.0 # singularclip singular value bound, clips into [1/c, c]
LR_LINEAR_DECAY: True
GAMMA: 0.99
LAMBDA: 0.65

SEQUENCE_LENGTH: 4

PRINT_NETWORK_SUMMARY: True
LOG_LAYER_GRAD_NORMS: True

# env specific
ENV_NAME: "Asterix-MinAtar"
ENV_KWARGS: {}

# evaluation
TEST_DURING_TRAINING: True 
TEST_INTERVAL: 0.05 # in terms of total updates
TEST_NUM_ENVS: 128
EPS_TEST: 0. # 0 for greedy policy
