seed: 0
state_dim: 5
dataset_size: 500000
dataset_seed_offset: 1001
total_steps: 20000
log_every: 20000
parseval_every: 1000
batch_size: 1024
num_tau: 51
num_atoms: 51
num_mog_components: 17
num_omega: 32
gamma: 0.95
immediate_reward_std: 0.1
omega_max: 15.0
huber_kappa: 1.0
lr: 0.001
max_grad_norm: 10.0
omega_clip: 15.0
omega_laplace_scale: 0.8
cf_loss_omega_eps: 0.001
sigma_min: 1e-06
sigma_max: 20.0
aux_mean_loss_weight: 0.1
c51_v_min: -25.0
c51_v_max: 25.0
embed_dim: 64
hidden_dim: 256
trunk_layers: 2
n_test: 10000
test_seed_offset: 7777
eval_chunk_size: 50
num_taus_iqn_eval: 2000
eval_iqn_seed: 42
eval_num_t: 201
eval_x_min: -15.0
eval_x_max: 15.0
eval_num_x: 301
risk_x_min: -200.0
risk_x_max: 200.0
risk_num_x: 2001
gp_t_delta: 0.0001
gp_num_t: 2001
cvar_alpha: 0.05
er_beta: 0.1
mv_lambda: 0.1
artifacts_dir: "/network/scratch/m/mousseat/purejaxql/figures/distribution_analysis/2026-04-26_13:45:46"
